% Extract time region of interest from signals

% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 15-Apr-2021 17:09:32

% Parameters
timeLimits = [0 0.1]; % seconds

%%
mpu6050_ROI = mpu6050_1300hz(:);
sampleRate = 1300; % Hz
startTime = 0; % seconds
minIdx = ceil(max((timeLimits(1)-startTime)*sampleRate,0))+1;
maxIdx = floor(min((timeLimits(2)-startTime)*sampleRate,length(mpu6050_ROI)-1))+1;
mpu6050_ROI = mpu6050_ROI(minIdx:maxIdx);

%%
adxl343_ROI = adxl343_550hz(:);
sampleRate = 550; % Hz
startTime = 0; % seconds
minIdx = ceil(max((timeLimits(1)-startTime)*sampleRate,0))+1;
maxIdx = floor(min((timeLimits(2)-startTime)*sampleRate,length(adxl343_ROI)-1))+1;
adxl343_ROI = adxl343_ROI(minIdx:maxIdx);

%%
adxl345_892Hz_ROI = adxl345_892Hz(:);
sampleRate = 890; % Hz
startTime = 0; % seconds
minIdx = ceil(max((timeLimits(1)-startTime)*sampleRate,0))+1;
maxIdx = floor(min((timeLimits(2)-startTime)*sampleRate,length(adxl345_892Hz_ROI)-1))+1;
adxl345_892Hz_ROI = adxl345_892Hz_ROI(minIdx:maxIdx);

plot(adxl345_892Hz_ROI)
hold on
plot(mpu6050_ROI)
hold on
plot (adxl343_ROI)
hold off

