name: Contribs
on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  contribs:
    runs-on: ubuntu-latest
    name: Contribs
    steps:
      - name: Contribs
        uses: carlescufi/action-contribs@main
        with:
          github-token: ${{ secrets.NCS_GITHUB_TOKEN }}
          command: 'external'
          messages: |
                    Thank you for your contribution!
                    It seems you are not a member of the nrfconnect GitHub organization.
                    At this time we are not accepting external contributions, but this may change soon.
                    Please visit https://devzone.nordicsemi.com/ to raise any issues you found or ask for help.
                    |
                    The author of this pull request has now been added to the nrfconnect GitHub organization.
          labels: 'external'
